import type { LucideIcon } from "lucide-react";
import {
  SpellCheck,
  FileSearch,
  Bot,
  ScanSearch,
  Wand2,
  Quote,
  GraduationCap,
  RefreshCw,
  MessageSquare,
  Sparkles,
  BarChart3,
  Mic2,
  BookOpen,
  ClipboardList,
  LineChart,
  UserCheck,
  Search,
  Award,
  Heart,
  FileUser,
  FileText,
  CircleDot,
  AlignLeft,
  Hash,
  Pilcrow,
  Type,
  Shield,
  PenLine,
  LayoutGrid,
  Languages,
} from "lucide-react";

export type ToolType = "ai" | "counter" | "page" | "redirect";

export interface WritingTool {
  slug: string;
  title: string;
  description: string;
  icon: LucideIcon;
  type: ToolType;
  category: string;
  /** Existing route to redirect to instead of /dashboard/tools/[slug] */
  href?: string;
  actionLabel?: string;
}

export const TOOL_CATEGORIES = [
  "Core",
  "Correctness",
  "AI Intelligence",
  "Rewrite & Tone",
  "Translation",
  "Research",
  "Text Analytics",
  "Productivity",
  "Brand & Style",
  "Career",
] as const;

export const WRITING_TOOLS: WritingTool[] = [
  {
    slug: "tools-hub",
    title: "All Writing Tools",
    description: "Browse every Grammarly-style tool in one place",
    icon: LayoutGrid,
    type: "page",
    category: "Core",
    href: "/dashboard/tools",
  },
  {
    slug: "grammar-checker",
    title: "Grammar Checker",
    description: "Catch grammar, spelling, and clarity issues",
    icon: SpellCheck,
    type: "ai",
    category: "Correctness",
    actionLabel: "Check Grammar",
  },
  {
    slug: "spell-checker",
    title: "Spell Checker",
    description: "Find and fix spelling mistakes",
    icon: SpellCheck,
    type: "ai",
    category: "Correctness",
    actionLabel: "Check Spelling",
  },
  {
    slug: "sentence-checker",
    title: "Sentence Checker",
    description: "Improve sentence structure and flow",
    icon: AlignLeft,
    type: "ai",
    category: "Correctness",
    actionLabel: "Check Sentences",
  },
  {
    slug: "punctuation-checker",
    title: "Punctuation Checker",
    description: "Fix commas, apostrophes, and more",
    icon: CircleDot,
    type: "ai",
    category: "Correctness",
    actionLabel: "Fix Punctuation",
  },
  {
    slug: "passive-voice-checker",
    title: "Passive Voice Checker",
    description: "Spot passive voice and suggest active rewrites",
    icon: RefreshCw,
    type: "ai",
    category: "Correctness",
    actionLabel: "Check Passive Voice",
  },
  {
    slug: "proofreader",
    title: "Proofreader",
    description: "Full proofread — grammar, style, and clarity",
    icon: FileSearch,
    type: "ai",
    category: "Correctness",
    actionLabel: "Proofread",
  },
  {
    slug: "plagiarism-checker",
    title: "Plagiarism Checker",
    description: "Check content originality",
    icon: Shield,
    type: "redirect",
    category: "AI Intelligence",
    href: "/dashboard/plagiarism",
  },
  {
    slug: "ai-detector",
    title: "AI Detector",
    description: "Estimate if text was AI-generated",
    icon: ScanSearch,
    type: "redirect",
    category: "AI Intelligence",
    href: "/dashboard/ai-detector",
  },
  {
    slug: "ai-humanizer",
    title: "AI Humanizer",
    description: "Make AI text sound naturally human",
    icon: Wand2,
    type: "redirect",
    category: "AI Intelligence",
    href: "/dashboard/humanizer",
  },
  {
    slug: "ai-agents",
    title: "AI Agents",
    description: "Specialized writing assistants for every task",
    icon: Bot,
    type: "page",
    category: "AI Intelligence",
    href: "/dashboard/tools/ai-agents",
  },
  {
    slug: "ai-chat",
    title: "AI Chat",
    description: "Chat with your writing assistant",
    icon: MessageSquare,
    type: "page",
    category: "AI Intelligence",
    href: "/dashboard/tools/ai-chat",
  },
  {
    slug: "paraphrase",
    title: "Paraphrasing Tool",
    description: "Rephrase text while keeping the same meaning",
    icon: RefreshCw,
    type: "ai",
    category: "Rewrite & Tone",
    actionLabel: "Paraphrase",
  },
  {
    slug: "translator",
    title: "Translator",
    description: "40+ languages with formality & domain control — Urdu, English, Arabic & more",
    icon: Languages,
    type: "page",
    category: "Translation",
    href: "/dashboard/tools/translator",
    actionLabel: "Translate",
  },
  {
    slug: "smart-rewrite",
    title: "Smart Rewrite",
    description: "8 rewrite modes — professional, shorter, persuasive, academic & more",
    icon: RefreshCw,
    type: "page",
    category: "Rewrite & Tone",
    href: "/dashboard/tools/smart-rewrite",
    actionLabel: "Rewrite",
  },
  {
    slug: "tone-detector",
    title: "Tone Detector",
    description: "Detect tone, formality, and voice",
    icon: Mic2,
    type: "ai",
    category: "Rewrite & Tone",
    actionLabel: "Detect Tone",
  },
  {
    slug: "citation-generator",
    title: "Citation Generator",
    description: "Create APA, MLA, and Chicago citations",
    icon: Quote,
    type: "ai",
    category: "Research",
    actionLabel: "Generate Citations",
  },
  {
    slug: "citation-finder",
    title: "Citation Finder",
    description: "Find claims that need sources",
    icon: Search,
    type: "ai",
    category: "Research",
    actionLabel: "Find Citations",
  },
  {
    slug: "essay-checker",
    title: "Essay Checker",
    description: "Review academic essays for structure and clarity",
    icon: GraduationCap,
    type: "ai",
    category: "Research",
    actionLabel: "Review Essay",
  },
  {
    slug: "word-counter",
    title: "Word Counter",
    description: "Count words, characters, and reading time",
    icon: Type,
    type: "counter",
    category: "Text Analytics",
  },
  {
    slug: "character-counter",
    title: "Character Counter",
    description: "Count characters with and without spaces",
    icon: Hash,
    type: "counter",
    category: "Text Analytics",
  },
  {
    slug: "paragraph-counter",
    title: "Paragraph Counter",
    description: "Count paragraphs in your text",
    icon: Pilcrow,
    type: "counter",
    category: "Text Analytics",
  },
  {
    slug: "sentence-counter",
    title: "Sentence Counter",
    description: "Count sentences and average length",
    icon: AlignLeft,
    type: "counter",
    category: "Text Analytics",
  },
  {
    slug: "snippets",
    title: "Snippets",
    description: "Save and reuse text snippets",
    icon: ClipboardList,
    type: "page",
    category: "Productivity",
    href: "/dashboard/tools/snippets",
  },
  {
    slug: "sop-reports",
    title: "SOP & Reports",
    description: "Generate SOPs, reports, and process guides from topics or explanations",
    icon: FileText,
    type: "page",
    category: "Productivity",
    href: "/dashboard/tools/sop-reports",
    actionLabel: "Generate Document",
  },
  {
    slug: "writing-analytics",
    title: "Analytics",
    description: "Your writing usage and AI activity",
    icon: LineChart,
    type: "page",
    category: "Productivity",
    href: "/dashboard/tools/analytics",
  },
  {
    slug: "brand-tones",
    title: "Brand Tones",
    description: "Brand voice profiles for consistent writing",
    icon: Mic2,
    type: "redirect",
    category: "Brand & Style",
    href: "/dashboard/brand-voice",
  },
  {
    slug: "style-guide",
    title: "Style Guide",
    description: "Team style rules and word preferences",
    icon: BookOpen,
    type: "redirect",
    category: "Brand & Style",
    href: "/dashboard/style-guide",
  },
  {
    slug: "authorship",
    title: "Authorship",
    description: "Analyze human vs AI writing signals",
    icon: UserCheck,
    type: "ai",
    category: "Brand & Style",
    actionLabel: "Analyze Authorship",
  },
  {
    slug: "ai-grader",
    title: "AI Grader",
    description: "Grade writing like an instructor",
    icon: Award,
    type: "ai",
    category: "Brand & Style",
    actionLabel: "Grade Writing",
  },
  {
    slug: "reader-reactions",
    title: "Reader Reactions",
    description: "See how different readers might react",
    icon: Heart,
    type: "ai",
    category: "Brand & Style",
    actionLabel: "Get Reactions",
  },
  {
    slug: "resume-builder",
    title: "Resume Builder",
    description: "Generate a professional resume with AI",
    icon: FileUser,
    type: "page",
    category: "Career",
    href: "/dashboard/tools/resume-builder",
  },
  {
    slug: "ai-writing-tools",
    title: "AI Writing Tools",
    description: "Templates and content generators",
    icon: Sparkles,
    type: "redirect",
    category: "Core",
    href: "/dashboard/templates",
  },
  {
    slug: "editor",
    title: "Writing Editor",
    description: "Full editor with grammar and AI rewrites",
    icon: PenLine,
    type: "redirect",
    category: "Core",
    href: "/dashboard/editor/new",
  },
];

export function getToolBySlug(slug: string): WritingTool | undefined {
  return WRITING_TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): WritingTool[] {
  return WRITING_TOOLS.filter((t) => t.category === category && t.slug !== "tools-hub");
}

export function getToolHref(tool: WritingTool): string {
  if (tool.href) return tool.href;
  if (tool.type === "counter" || tool.type === "ai") {
    return `/dashboard/tools/${tool.slug}`;
  }
  return `/dashboard/tools/${tool.slug}`;
}
