export const TONE_CATEGORIES = [
  "Professional",
  "Friendly",
  "Confident",
  "Persuasive",
  "Casual",
  "Formal",
  "Warm",
  "Direct",
  "Empathetic",
  "Luxury",
  "Bold",
  "Educational",
  "Sales-focused",
  "Authoritative",
] as const;

export type ToneCategory = (typeof TONE_CATEGORIES)[number];

export const REWRITE_ACTION_LABELS: Record<string, string> = {
  grammar_fix: "Fix Grammar",
  spelling_fix: "Fix Spelling",
  punctuation_fix: "Fix Punctuation",
  improve_clarity: "Improve Clarity",
  make_professional: "Make More Professional",
  make_friendly: "Make More Friendly",
  make_persuasive: "Make More Persuasive",
  make_concise: "Make More Concise",
  expand: "Expand Text",
  simplify: "Simplify Text",
  rewrite_sentence: "Rewrite Sentence",
  rewrite_paragraph: "Rewrite Paragraph",
  change_tone: "Change Tone",
  summarize: "Summarize",
  continue_writing: "Continue Writing",
  improve_readability: "Improve Readability",
  make_seo_friendly: "Make SEO-Friendly",
  make_brand_aligned: "Make Brand-Aligned",
  features_to_benefits: "Convert Features to Benefits",
  rewrite_amazon: "Rewrite for Amazon Listing",
  rewrite_linkedin: "Rewrite for LinkedIn",
  rewrite_email: "Rewrite for Email",
  rewrite_website: "Rewrite for Website Copy",
};
