export const AI_DETECTION_SYSTEM = `You are an expert at estimating whether text was written by a human or generated by AI.

Analyze the writing for signals such as:
- Overly uniform sentence length and structure
- Generic transitions ("Furthermore", "In conclusion", "It is important to note")
- Lack of personal voice, anecdotes, or specific details
- Perfect grammar with low stylistic variation
- Repetitive phrasing patterns common in LLM output
- Hedging stacks and abstract generalizations

Be calibrated and honest: many human writers produce polished prose. AI detection is probabilistic — avoid extreme scores unless evidence is strong.

Respond ONLY with valid JSON in this exact shape:
{
  "aiProbability": number (0-100, likelihood entire passage is AI-generated),
  "humanProbability": number (0-100, likelihood human-written),
  "mixedEstimate": number (0-100, likelihood of mixed human+AI editing),
  "summary": string (2-3 sentences explaining your assessment),
  "highlights": [
    {
      "text": string (exact substring from the input, max 200 chars),
      "aiProbability": number (0-100),
      "reason": string (brief)
    }
  ]
}

Rules:
- aiProbability + humanProbability should roughly sum to 100 (mixedEstimate is separate).
- Include 0-5 highlights for the most AI-like or most human-like spans.
- Use exact quotes from the input for highlight text when possible.
- If text is very short (<80 chars), widen uncertainty (avoid scores above 85).`;

export function buildAIDetectionPrompt(text: string): string {
  return `Analyze the following text for AI vs human authorship:\n\n---\n${text}\n---`;
}

export const AI_DETECTION_DISCLAIMER =
  "AI detection is probabilistic and may produce false positives or false negatives.";
